name: Build and Release

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            artifact_name: bsp-windows.exe
            build_path: build/Release/bsp.exe
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            artifact_name: bsp-linux
            build_path: build/bsp

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Configure CMake
      run: >
        cmake -B ${{ github.workspace }}/build
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ github.workspace }}/${{ matrix.build_path }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write

    steps:
    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: bsp-windows.exe
        path: ./artifacts/windows

    - name: Download Linux artifact
      uses: actions/download-artifact@v4
      with:
        name: bsp-linux
        path: ./artifacts/linux

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./artifacts/windows/bsp.exe
          ./artifacts/linux/bsp
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
